import "./globals.css";
import { Header } from "../components/layouts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"font-[GeneralSans]"}>
        <Header />
        <div className="mt-[79.5px]">{children}</div>
      </body>
    </html>
  );
}
